services:
  aws-cdk-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - package.json
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: .env
          target: /app/.env
